### ISSUE TITLE
System Shock (2023) SUWSF v3 might be broken after 1.2 update

### ISSUE THREAD

**Issue by Hoshi82** [Lyall/UltrawidePatches#3]
As topic says the ultrawide fix for System Shock seems not to be working anymore after the 1.2 update of the game. Would it be possible to update it? I tried this one uploaded here: https://www.wsgf.org/dr/system-shock-2023/en

**Comment by Lyall** [comment]
Just installing it again at the moment. I should be able to have a look tonight.

**Comment by Lyall** [comment]
Okay I've updated it for v1.2. Give it a try and let me know if you run in to any problems.

**Comment by Hoshi82** [comment]
It worked, thanks! :)

**Comment by Lyall** [comment]
Awesome, glad to hear it.
