### ISSUE TITLE
[Request] Phantom Fury

### ISSUE THREAD

**Issue by Hoshi82** [Lyall/UltrawidePatches#4]
Sadly it's another UE4 game where the devs didn't implement the ultrawide aspect ratios propperly. Engin.ini tweaks like AspectRatioAxisConstraint=AspectRatio_MaintainYFOV don't work and the wider we go the closer the weapons/hand of the playercharacter gets zoomed in, besides the world zoomed in as usual.

It would be super nice if you could look into this and maybe an ultrawide fix is possible. :)

**Comment by Lyall** [comment]
I had a look within the two hour window of steam refunds and it looks fixable but it would probably need to be it's own fix. The scope of what needs to be changed is beyond tools like SUWSF. Probably not on the cards right now, at least until the game is cheap and I can look at it for longer than 2 hours!

Before:
![Phoenix-Win64-Shipping_2024_04_25_23_05_04_761](https://github.com/Lyall/UltrawidePatches/assets/695941/6e7eb9c6-e3a5-4d82-af6b-fca4b648f150)
After:
![Phoenix-Win64-Shipping_2024_04_25_23_05_42_304](https://github.com/Lyall/UltrawidePatches/assets/695941/a97e059f-2ecc-4bcc-8f87-c7e6e39aa124)

**Comment by Hoshi82** [comment]
Ok, thanks for looking into it.:)
