### ISSUE TITLE
Black Myth Wukong: add FOV option

### ISSUE THREAD

**Issue by Keith94** [Lyall/UltrawidePatches#5]
Can it be added? Didn't find a reliable FOV solution aside from dev console.

**Comment by sole-less** [comment]
I am looking for a solution for this same issue! I saw the option for Unreal Unlocker, but none of the console shortcuts work for me

**Comment by Lyall** [comment]
That would be outside the scope of what I could accomplish with SUWSF. I would need to write a fix specifically for Wukong. If there's enough demand for it I can have a look but for now it's not on the cards.

**Comment by Keith94** [comment]
I think with over 2 million players there should (hopefully) be some demand! 🥲 But if someone else makes a fix I will mark this resolved.

**Comment by Lyall** [comment]
Closing this issue and directing users to #7 .
