### ISSUE TITLE
Black Myth Wukong: Request

### ISSUE THREAD

**Issue by p1xel8ted** [Lyall/UltrawidePatches#7]
If you decide to write your own fix, I humbly request, if able:

- Previously requested, but FOV adjustment (UUU5 no good)
- Disable the camera blur around the edges of the screen
- Modifying sharpening value, instead of full disable (by percentage perhaps)
- Vignette can be disabled via INI, but if simple enough to code, why not, AIO solution etc etc

**Comment by p1xel8ted** [comment]
For those that stumble across this:

Download https://www.nexusmods.com/blackmythwukong/mods/19?tab=files and install as instructed
Run game, use F10 to open the console,
Change FOV using 'fov value' i.e. fov 110
Change level of sharpening using 'r.Tonemapper.Sharpen value' i.e r.Tonemapper.Sharpen 2

**Comment by Lyall** [comment]
I've written something for the game [over here](https://github.com/Lyall/WukongTweak).

So far I've got sharpening, vignette and chromatic aberration tweaks in. Also got gameplay FOV (though it needs more testing) in. I didn't find any examples of camera blur near the edges in the section of the game I'm in. Maybe it shows up later? There are some references to a post process radial blur which fits the description, thought it has no CVar to control it.

**Comment by p1xel8ted** [comment]
> I've written something for the game [over here](https://github.com/Lyall/WukongTweak).
> 
> So far I've got sharpening, vignette and chromatic aberration tweaks in. Also got gameplay FOV (though it needs more testing) in. I didn't find any examples of camera blur near the edges in the section of the game I'm in. Maybe it shows up later? There are some references to a post process radial blur which fits the description, thought it has no CVar to control it.

Ok, after some testing, it's the low health effect. (And thanks for the aio, works great)

**Comment by Lyall** [comment]
Alright, gonna consider this issue resolved since the request has been fulfilled. If you still want me to look at the radial camera blur @p1xel8ted, can you create an issue on that new repo? I can look in to it further if you like.
