### ISSUE TITLE
Black Myth Wukong Question: Does it support 16:10 display?

### ISSUE THREAD

**Issue by DoubleTrust** [Lyall/UltrawidePatches#8]
May I ask whether this mod supports 16:10 screen display?

**Comment by DoubleTrust** [comment]
Sincerely wish that the mod can support 16:10. That would be awesome!

**Comment by Lyall** [comment]
Gonna direct you to [this project](https://github.com/Lyall/WukongTweak). I will see if it's possible to add 16:10 support to that. If you have any further requests or anything related to Wukong, put them in the issues section of that repository.
