### ISSUE TITLE
Would this work for 16:10?

### ISSUE THREAD

**Issue by SynStark** [Lyall/UltrawidePatches#9]
I'm playing on Asus Scar 18 with 16:10 resolution.

I used the HxD software using the CD CC CC 3F values for 16:10 but the problem is where I go into the menu, it's too zoomed and I'm missing some gameplay screen. Around 1cm on both left and right side probably. I tried changing the FOV but it doesn't affect the game menu screen for some reason.
So would this work better for 16:10?

Thank you!

![Screenshot 2024-09-03 152624](https://github.com/user-attachments/assets/b9951f02-dd92-49b3-87e7-30026ef6c5b9)

**Comment by Lyall** [comment]
[WukongTweak](https://github.com/Lyall/WukongTweak) should work at 16:10 if you want to try that. I've explicitly added support for it.

**Comment by SynStark** [comment]
> [WukongTweak](https://github.com/Lyall/WukongTweak) should work at 16:10 if you want to try that. I've explicitly added support for it.

Just tried it. Works great for the moment. Thank you very much for the response!
